/*
 * Created on 25 dic 2017 ( Time 21:05:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.riphouse.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import org.riphouse.dto.Esenzioneassisitito;
import org.riphouse.dao.EsenzioneassisititoDAO;
import org.riphouse.dao.impl.jdbc.commons.GenericDAO;

/**
 * Esenzioneassisitito DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class EsenzioneassisititoDAOImpl extends GenericDAO<Esenzioneassisitito> implements EsenzioneassisititoDAO {

	private final static String SQL_SELECT = 
		"select id, Esenzione, Assisitito from esenzioneassisitito where id = ?";

	private final static String SQL_INSERT = 
		"insert into esenzioneassisitito ( Esenzione, Assisitito ) values ( ?, ? )";

	private final static String SQL_UPDATE = 
		"update esenzioneassisitito set Esenzione = ?, Assisitito = ? where id = ?";

	private final static String SQL_DELETE = 
		"delete from esenzioneassisitito where id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from esenzioneassisitito";

	private final static String SQL_COUNT = 
		"select count(*) from esenzioneassisitito where id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public EsenzioneassisititoDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param id;
	 * @return the new instance
	 */
	private Esenzioneassisitito newInstanceWithPrimaryKey( Long id ) {
		Esenzioneassisitito esenzioneassisitito = new Esenzioneassisitito();
		esenzioneassisitito.setId( id );
		return esenzioneassisitito ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param id;
	 * @return the bean found or null if not found 
	 */
	@Override
	public Esenzioneassisitito find( Long id ) {
		Esenzioneassisitito esenzioneassisitito = newInstanceWithPrimaryKey( id ) ;
		if ( super.doSelect(esenzioneassisitito) ) {
			return esenzioneassisitito ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param esenzioneassisitito
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( Esenzioneassisitito esenzioneassisitito ) {
		return super.doSelect(esenzioneassisitito) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param esenzioneassisitito
	 */
	@Override
	public Long insert(Esenzioneassisitito esenzioneassisitito) {
		Long key = super.doInsertAutoIncr(esenzioneassisitito);
		return key.longValue();
	}

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param esenzioneassisitito
	 * @return
	 */
	@Override
	public int update(Esenzioneassisitito esenzioneassisitito) {
		return super.doUpdate(esenzioneassisitito);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param id;
	 * @return
	 */
	@Override
	public int delete( Long id ) {
		Esenzioneassisitito esenzioneassisitito = newInstanceWithPrimaryKey( id ) ;
		return super.doDelete(esenzioneassisitito);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param esenzioneassisitito
	 * @return
	 */
	@Override
	public int delete( Esenzioneassisitito esenzioneassisitito ) {
		return super.doDelete(esenzioneassisitito);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param id;
	 * @return
	 */
	@Override
	public boolean exists( Long id ) {
		Esenzioneassisitito esenzioneassisitito = newInstanceWithPrimaryKey( id ) ;
		return super.doExists(esenzioneassisitito);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param esenzioneassisitito
	 * @return
	 */
	@Override
	public boolean exists( Esenzioneassisitito esenzioneassisitito ) {
		return super.doExists(esenzioneassisitito);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, Esenzioneassisitito esenzioneassisitito) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, esenzioneassisitito.getId() ) ; // "id" : java.lang.Long
	}

    //----------------------------------------------------------------------
	@Override
	protected Esenzioneassisitito populateBean(ResultSet rs, Esenzioneassisitito esenzioneassisitito) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		esenzioneassisitito.setId(rs.getLong("id")); // java.lang.Long
		if ( rs.wasNull() ) { esenzioneassisitito.setId(null); }; // not primitive number => keep null value if any
		esenzioneassisitito.setEsenzione(rs.getLong("Esenzione")); // java.lang.Long
		if ( rs.wasNull() ) { esenzioneassisitito.setEsenzione(null); }; // not primitive number => keep null value if any
		esenzioneassisitito.setAssisitito(rs.getLong("Assisitito")); // java.lang.Long
		if ( rs.wasNull() ) { esenzioneassisitito.setAssisitito(null); }; // not primitive number => keep null value if any
		return esenzioneassisitito ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, Esenzioneassisitito esenzioneassisitito) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		// "id" is auto-incremented => no set in insert		
		setValue(ps, i++, esenzioneassisitito.getEsenzione() ) ; // "Esenzione" : java.lang.Long
		setValue(ps, i++, esenzioneassisitito.getAssisitito() ) ; // "Assisitito" : java.lang.Long
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, Esenzioneassisitito esenzioneassisitito) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, esenzioneassisitito.getEsenzione() ) ; // "Esenzione" : java.lang.Long
		setValue(ps, i++, esenzioneassisitito.getAssisitito() ) ; // "Assisitito" : java.lang.Long
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, esenzioneassisitito.getId() ) ; // "id" : java.lang.Long
	}

}
