/*
 * Created on 25 dic 2017 ( Time 21:05:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.riphouse.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.ejb.Local;
import javax.ejb.Stateless;

import org.riphouse.dto.Recapito;
import org.riphouse.dao.RecapitoDAO;
import org.riphouse.dao.impl.jdbc.commons.GenericDAO;

@Local(RecapitoDAO.class)
@Stateless
public class RecapitoDAOImpl extends GenericDAO<Recapito> implements RecapitoDAO {

	private final static String SQL_SELECT = 
		"select id, TipoRecapito, ValoreRecapito from recapito where id = ?";

	private final static String SQL_INSERT = 
		"insert into recapito ( TipoRecapito, ValoreRecapito ) values ( ?, ? )";

	private final static String SQL_UPDATE = 
		"update recapito set TipoRecapito = ?, ValoreRecapito = ? where id = ?";

	private final static String SQL_DELETE = 
		"delete from recapito where id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from recapito";

	private final static String SQL_COUNT = 
		"select count(*) from recapito where id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public RecapitoDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param id;
	 * @return the new instance
	 */
	private Recapito newInstanceWithPrimaryKey( Long id ) {
		Recapito recapito = new Recapito();
		recapito.setId( id );
		return recapito ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param id;
	 * @return the bean found or null if not found 
	 */
	@Override
	public Recapito find( Long id ) {
		Recapito recapito = newInstanceWithPrimaryKey( id ) ;
		if ( super.doSelect(recapito) ) {
			return recapito ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param recapito
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( Recapito recapito ) {
		return super.doSelect(recapito) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param recapito
	 */
	@Override
	public Long insert(Recapito recapito) {
		Long key = super.doInsertAutoIncr(recapito);
		return key.longValue();
	}

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param recapito
	 * @return
	 */
	@Override
	public int update(Recapito recapito) {
		return super.doUpdate(recapito);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param id;
	 * @return
	 */
	@Override
	public int delete( Long id ) {
		Recapito recapito = newInstanceWithPrimaryKey( id ) ;
		return super.doDelete(recapito);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param recapito
	 * @return
	 */
	@Override
	public int delete( Recapito recapito ) {
		return super.doDelete(recapito);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param id;
	 * @return
	 */
	@Override
	public boolean exists( Long id ) {
		Recapito recapito = newInstanceWithPrimaryKey( id ) ;
		return super.doExists(recapito);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param recapito
	 * @return
	 */
	@Override
	public boolean exists( Recapito recapito ) {
		return super.doExists(recapito);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, Recapito recapito) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, recapito.getId() ) ; // "id" : java.lang.Long
	}

    //----------------------------------------------------------------------
	@Override
	protected Recapito populateBean(ResultSet rs, Recapito recapito) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		recapito.setId(rs.getLong("id")); // java.lang.Long
		if ( rs.wasNull() ) { recapito.setId(null); }; // not primitive number => keep null value if any
		recapito.setTiporecapito(rs.getLong("TipoRecapito")); // java.lang.Long
		if ( rs.wasNull() ) { recapito.setTiporecapito(null); }; // not primitive number => keep null value if any
		recapito.setValorerecapito(rs.getString("ValoreRecapito")); // java.lang.String
		return recapito ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, Recapito recapito) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		// "id" is auto-incremented => no set in insert		
		setValue(ps, i++, recapito.getTiporecapito() ) ; // "TipoRecapito" : java.lang.Long
		setValue(ps, i++, recapito.getValorerecapito() ) ; // "ValoreRecapito" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, Recapito recapito) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, recapito.getTiporecapito() ) ; // "TipoRecapito" : java.lang.Long
		setValue(ps, i++, recapito.getValorerecapito() ) ; // "ValoreRecapito" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, recapito.getId() ) ; // "id" : java.lang.Long
	}

}
