/*
 * Created on 25 dic 2017 ( Time 21:05:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.riphouse.dto;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'Assistito' entity
 * 
 * @author Telosys Tools
 *
 */
public class Assistito implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id BIGINT 
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : anagrafica BIGINT 
    private Long anagrafica;

    // DB : dataScadenzaLibrettoSanitario DATE 
    private Date datascadenzalibrettosanitario;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAnagrafica( Long anagrafica ) {
        this.anagrafica = anagrafica;
    }
    public Long getAnagrafica() {
        return this.anagrafica;
    }

    public void setDatascadenzalibrettosanitario( Date datascadenzalibrettosanitario ) {
        this.datascadenzalibrettosanitario = datascadenzalibrettosanitario;
    }
    public Date getDatascadenzalibrettosanitario() {
        return this.datascadenzalibrettosanitario;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(anagrafica);
        sb.append("|");
        sb.append(datascadenzalibrettosanitario);
        return sb.toString(); 
    } 


}
