/*
 * Created on 25 dic 2017 ( Time 21:05:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.riphouse.dto;

import java.io.Serializable;


/**
 * Java bean for 'Camera' entity
 * 
 * @author Telosys Tools
 *
 */
public class Camera implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id BIGINT 
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : Repato BIGINT 
    private Long repato;

    // DB : NumeroPosti INT 
    private Integer numeroposti;

    // DB : NumeroCamera INT 
    private Integer numerocamera;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRepato( Long repato ) {
        this.repato = repato;
    }
    public Long getRepato() {
        return this.repato;
    }

    public void setNumeroposti( Integer numeroposti ) {
        this.numeroposti = numeroposti;
    }
    public Integer getNumeroposti() {
        return this.numeroposti;
    }

    public void setNumerocamera( Integer numerocamera ) {
        this.numerocamera = numerocamera;
    }
    public Integer getNumerocamera() {
        return this.numerocamera;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(repato);
        sb.append("|");
        sb.append(numeroposti);
        sb.append("|");
        sb.append(numerocamera);
        return sb.toString(); 
    } 


}
