/*
 * Created on 25 dic 2017 ( Time 21:05:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.riphouse.dto;

import java.io.Serializable;


/**
 * Java bean for 'Caregiverassistito' entity
 * 
 * @author Telosys Tools
 *
 */
public class Caregiverassistito implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id BIGINT 
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : CareGiver BIGINT 
    private Long caregiver;

    // DB : Assisitito BIGINT 
    private Long assisitito;

    // DB : TipoCareGiver VARCHAR 
    private String tipocaregiver;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCaregiver( Long caregiver ) {
        this.caregiver = caregiver;
    }
    public Long getCaregiver() {
        return this.caregiver;
    }

    public void setAssisitito( Long assisitito ) {
        this.assisitito = assisitito;
    }
    public Long getAssisitito() {
        return this.assisitito;
    }

    public void setTipocaregiver( String tipocaregiver ) {
        this.tipocaregiver = tipocaregiver;
    }
    public String getTipocaregiver() {
        return this.tipocaregiver;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(caregiver);
        sb.append("|");
        sb.append(assisitito);
        sb.append("|");
        sb.append(tipocaregiver);
        return sb.toString(); 
    } 


}
