/*
 * Created on 25 dic 2017 ( Time 21:05:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.riphouse.dto;

import java.io.Serializable;


/**
 * Java bean for 'Letto' entity
 * 
 * @author Telosys Tools
 *
 */
public class Letto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id BIGINT 
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : NumeroLetto VARCHAR 
    private String numeroletto;

    // DB : Camera BIGINT 
    private Long camera;

    // DB : Telefono VARCHAR 
    private String telefono;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNumeroletto( String numeroletto ) {
        this.numeroletto = numeroletto;
    }
    public String getNumeroletto() {
        return this.numeroletto;
    }

    public void setCamera( Long camera ) {
        this.camera = camera;
    }
    public Long getCamera() {
        return this.camera;
    }

    public void setTelefono( String telefono ) {
        this.telefono = telefono;
    }
    public String getTelefono() {
        return this.telefono;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(numeroletto);
        sb.append("|");
        sb.append(camera);
        sb.append("|");
        sb.append(telefono);
        return sb.toString(); 
    } 


}
