/*
 * Created on 25 dic 2017 ( Time 21:05:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.riphouse.dto;

import java.io.Serializable;


/**
 * Java bean for 'Reparto' entity
 * 
 * @author Telosys Tools
 *
 */
public class Reparto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id BIGINT 
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : NomeReparto VARCHAR 
    private String nomereparto;

    // DB : Piano BIGINT 
    private Long piano;

    // DB : Residenza BIGINT 
    private Long residenza;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNomereparto( String nomereparto ) {
        this.nomereparto = nomereparto;
    }
    public String getNomereparto() {
        return this.nomereparto;
    }

    public void setPiano( Long piano ) {
        this.piano = piano;
    }
    public Long getPiano() {
        return this.piano;
    }

    public void setResidenza( Long residenza ) {
        this.residenza = residenza;
    }
    public Long getResidenza() {
        return this.residenza;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(nomereparto);
        sb.append("|");
        sb.append(piano);
        sb.append("|");
        sb.append(residenza);
        return sb.toString(); 
    } 


}
