/*
 * Created on 25 dic 2017 ( Time 21:05:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.riphouse.dao.impl.jdbc.commons;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

/**
 * DataSource provider
 * 
 * @author Telosys Tools
 *
 */
public class DataSourceProvider {
	
	private static String name = "java:/jdbc/vecho";
	
	/**
	 * The unique DataSource instance (singleton)
	 */
	private final static DataSource datasource = createDataSource() ;
	
	public static DataSource getDataSource() {
		return datasource;
	}
	
	

	private static DataSource createDataSource() {
		DataSource ds = null;
		try {
				Context context = new InitialContext();
				ds = (DataSource) context.lookup(name);
		} catch ( NamingException e) {
			throw new ExceptionInInitializerError(e);
		}
		return ds;
	}

	
}
