/*
 * Created on 25 dic 2017 ( Time 21:05:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.riphouse.dao;

import org.riphouse.dto.Recapito;

/**
 * Recapito DAO interface
 * 
 * @author Telosys Tools
 */
public interface RecapitoDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param id
	 * @return the bean found or null if not found 
	 */
	public Recapito find( Long id ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param recapito
	 * @return true if found, false if not found
	 */
	public boolean load( Recapito recapito ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param recapito
	 * @return the generated value for the auto-incremented column
	 */
	public Long insert(Recapito recapito) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param recapito
	 * @return
	 */
	public int update(Recapito recapito) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param id
	 * @return
	 */
	public int delete( Long id ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param recapito
	 * @return
	 */
	public int delete( Recapito recapito ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param id
	 * @return
	 */
	public boolean exists( Long id ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param recapito
	 * @return
	 */
	public boolean exists( Recapito recapito ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
